[project]
name = "shopping-mall-call-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.2",
    "google-genai>=1.62.0",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
]
